<?php

/**
 * @file
 * Contains bms_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bms_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bms_core module.
    case 'help.page.bms_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bud core module') . '</p>';
      return $output;

    default:
  }
}
